[package]
name = "vernamvault"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
perf = "warn"
style = "warn"
complexity = "warn"
suspicious = "warn"
correctness = "warn"
